import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AnnouncementBar from "@/components/AnnouncementBar";

import Footer from "@/components/Footer";
import FloatingCalendarBadge from "@/components/FloatingCalendarBadge";
import ExitIntentPopup from "@/components/ExitIntentPopup";
import ScrollLeadCapture from "@/components/ScrollLeadCapture";
import SmartLeadMagnetBanner from "@/components/SmartLeadMagnetBanner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} font-inter antialiased`}
      >
        <AnnouncementBar />
        <Header />
        {children}
       
        <FloatingCalendarBadge />
        <ExitIntentPopup />
        <ScrollLeadCapture />
        <SmartLeadMagnetBanner />
        <Footer />
      </body>
    </html>
  );
}
